spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example
    username: root
    password: root
    platform: mysql
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

server:
  port: 8081
