global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
    - job_name: 'prometheus'
  static_configs:
    - targets: ['127.0.0.1:9090']

  - job_name: 'hibernate-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
  - targets: ['HOST_IP:8081']
